language: C
addons:
 apt:
  packages:
   - libkeyutils-dev
   - libattr1-dev
   - attr
   - openssl
   - libssl-dev
   - asciidoc
   - xsltproc
   - docbook-xsl
   - docbook-xml
matrix:
   include:
     - env: TSS=ibmtss SSL=openssl
# libressl is failing
#    - env: TSS=ibmtss SSL=libressl;
     - env: TSS=tpm2-tss SSL=openssl

before_install:
   - if [ "${SSL}" = "libressl" ]; then
        ./tests/install-libressl.sh;
     fi
   - if [ "${SSL}" = "openssl" ]; then
        ./tests/install-gost-engine.sh;
        openssl version;
     fi

install:
   - if [ "${TSS}" = "ibmtss" ]; then
           ./tests/install-tss.sh;
           ./tests/install-swtpm.sh;
     fi
   - if [ "${TSS}" = "tpm2-tss" ]; then
           sudo apt-get install lcov pandoc autoconf-archive liburiparser-dev;
           sudo apt-get install libdbus-1-dev libglib2.0-dev dbus-x11 libgcrypt-dev;
           sudo apt-get install libssl-dev doxygen libjson-c-dev;
           sudo apt-get install libini-config-dev libltdl-dev;
          ./tests/install-tpm2-tss.sh;
     fi

script:
   - if [ "${SSL}" = "libressl" ]; then
       export PKG_CONFIG_PATH="/opt/libressl/lib/pkgconfig:$PKG_CONFIG_PATH";
       export LIBCRYPTO_CFLAGS="$(pkg-config --cflags-only-I --libs-only-L libressl-libcrypto)";
     fi

# Needed for gost engine support
   - if [ "${SSL}" = "openssl" ]; then
       export LDFLAGS=-L/usr/local/lib64;
       export LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/lib;
       export PATH=/usr/local/bin:$PATH;
       export C_INCLUDE_PATH=/usr/local/include:/usr/include:$C_INCLUDE_PATH;
     fi

   - autoreconf -i && ./configure && make -j$(nproc) && sudo make install && VERBOSE=1 make check;

   - tail -3 tests/ima_hash.log;
   - tail -3 tests/sign_verify.log;

# Without a HW TPM, the boot_aggregate test requires initializing a software
# TPM based on the TPM event log.
   - if [ "${TSS}" = "ibmtss" ]; then
       tail -3 tests/boot_aggregate.log;
     fi
